# Generated by Django 3.1.5 on 2021-03-12 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kitchen_refrig', models.BooleanField()),
                ('kitchen_oven', models.BooleanField()),
                ('kitchen_disposal', models.BooleanField()),
                ('kitchen_cabinets', models.BooleanField(null=True)),
                ('kitchen_dishwasher', models.BooleanField()),
                ('kitchen_fan_hood', models.BooleanField()),
                ('kitchen_microwave', models.BooleanField()),
                ('kitchen_description', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('materials_condition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.materialsandcondition')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.CharField(choices=[('HOME', 'Home'), ('GENERAL', 'General'), ('SITE', 'Site'), ('PROPERTY', 'Property'), ('OFFSITE', 'Offsite'), ('ROOMS', 'Rooms'), ('AMENITIES', 'Amenities'), ('NEIGHBORHOOD', 'Neighborhood'), ('UTILITIES', 'Utilities'), ('BASEMENT', 'Basement'), ('KITCHEN', 'Kitchen'), ('FOUNDATION', 'Foundation'), ('MAT_COND', 'Mat Cond'), ('DESC_IMPROV', 'Desc Improv')], max_length=20)),
                ('img', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('description', models.CharField(default='', max_length=150)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.house')),
            ],
        ),
    ]
