# Generated by Django 3.1.5 on 2021-02-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210124_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(choices=[('APPRAISER', 'Appraiser'), ('CUSTOMER', 'Customer requesting appraisal')]),
        ),
    ]
