# Generated by Django 3.1.5 on 2021-03-18 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210313_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basement',
            name='materials_conditions',
        ),
        migrations.RemoveField(
            model_name='foundation',
            name='improvements_id',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='materials_condition',
        ),
        migrations.RemoveField(
            model_name='utilities',
            name='materials_conditions',
        ),
        migrations.AddField(
            model_name='basement',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.house'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foundation',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.house'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchen',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.house'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilities',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.house'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foundation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen_cabinets',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
