# Generated by Django 3.1.5 on 2021-02-22 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_appraisal'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('street_address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip', models.TextField()),
                ('county', models.TextField()),
                ('appraisal_status', models.TextField()),
                ('appraiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseFeatures',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pool', models.TextField()),
                ('fireplace', models.TextField()),
                ('patio', models.TextField()),
                ('deck', models.TextField()),
                ('fence', models.TextField()),
                ('garage', models.TextField()),
                ('basement', models.TextField()),
                ('attic', models.TextField()),
                ('comments', models.TextField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.house')),
            ],
        ),
        migrations.DeleteModel(
            name='Appraisal',
        ),
    ]
