# Generated by Django 3.1.5 on 2021-03-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210318_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='page',
            field=models.CharField(choices=[('HOME', 'Home'), ('GENERAL', 'General'), ('SITE', 'Site'), ('PROPERTY', 'Property'), ('OFFSITE', 'Offsite'), ('ROOMS', 'Rooms'), ('AMENITIES', 'Amenities'), ('NEIGHBORHOOD', 'Neighborhood'), ('UTILITIES', 'Utilities'), ('BASEMENT', 'Basement'), ('KITCHEN', 'Kitchen'), ('FOUNDATION', 'Foundation'), ('MATERIALS_CONDITIONS', 'Materials Conditions'), ('DESC_IMPROV', 'Desc Improv'), ('APPRAISAL', 'Appraisal')], max_length=20),
        ),
    ]
