# Generated by Django 3.1.5 on 2021-02-22 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_appraisal_basement_descriptionofimprovements_foundation_kitchen_materialsandcondition_offsite_proper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('name', models.IntegerField()),
                ('built_up', models.TextField()),
                ('growth_rate', models.TextField()),
                ('property_value', models.TextField()),
                ('demand_supply', models.TextField()),
                ('marketability_factors', models.TextField()),
                ('market_conditions', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.house')),
            ],
        ),
    ]
