# Generated by Django 3.1.5 on 2021-03-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210318_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='cooling_condition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='cooling_type',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='heat_fuel',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
