# Generated by Django 3.1.5 on 2021-02-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='demand_supply',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='supply_demand',
            field=models.TextField(choices=[('SHORTAGE', 'Shortage'), ('STABLE', 'Stable'), ('DECLINING', 'Declining')], default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialsandcondition',
            name='condition_bath_floor',
            field=models.TextField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='materialsandcondition',
            name='condition_bath_wainscot',
            field=models.TextField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='materialsandcondition',
            name='condition_doors',
            field=models.TextField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='materialsandcondition',
            name='condition_floors',
            field=models.TextField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='materialsandcondition',
            name='condition_trim',
            field=models.TextField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='materialsandcondition',
            name='condition_walls',
            field=models.TextField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='built_up',
            field=models.TextField(choices=[('OVER75', 'Over 75%'), ('UNDER75', '25%-75%'), ('UNDER25', 'Under 25%')]),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='growth_rate',
            field=models.TextField(choices=[('RAPID', 'Rapid'), ('STABLE', 'Stable'), ('SLOW', 'Slow')]),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.TextField(choices=[('URBAN', 'Urban'), ('SUBURBAN', 'Suburban'), ('RURAL', 'Rural')]),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_alley',
            field=models.TextField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('NEITHER', 'Neither')]),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_curb',
            field=models.TextField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('NEITHER', 'Neither')]),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_sidewalk',
            field=models.TextField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('NEITHER', 'Neither')]),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_street',
            field=models.TextField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('NEITHER', 'Neither')]),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_streetlights',
            field=models.TextField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('NEITHER', 'Neither')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.TextField(choices=[('FOYER', 'Foyer'), ('LIVING', 'Living Room'), ('DINING', 'Dining Room'), ('KITCHEN', 'Kitchen'), ('DEN', 'Den'), ('FAMILY', 'Family Room'), ('RECREATION', 'Recreation Room'), ('BEDROOM', 'Bedroom'), ('BATH', 'Bath'), ('HALF_BATH', 'Half Bath'), ('LAUNDRY', 'Laundry'), ('BASEMENT', 'Basement')]),
        ),
        migrations.AlterField(
            model_name='site',
            name='zone_compliance',
            field=models.TextField(choices=[('LEGAL', 'LEGAL'), ('LEGAL_NONCONF', 'Legal Nonconforming (grandfathered use)'), ('ILLEGAL', 'Illegal'), ('NO_ZONING', 'No Zoning')]),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='cooling_condition',
            field=models.TextField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')]),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='heat_condition',
            field=models.TextField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('POOR', 'Poor')]),
        ),
    ]
