# Generated by Django 3.1.5 on 2021-04-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210322_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='hoa_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
