# Generated by Django 3.1.5 on 2021-02-22 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0007_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='customer',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='appraiser',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appraiser', to='auth.user'),
            preserve_default=False,
        ),
    ]
