# Generated by Django 3.1.5 on 2021-02-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210222_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='borrower',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='current_owner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='occupant',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Tenant', 'Tenant'), ('Vacant', 'Vacant')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Planned Unit Development', 'Pud'), ('Condominium', 'Condominium')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_rights_appraised',
            field=models.CharField(blank=True, choices=[('Fee Simple', 'Fee Simple'), ('Leasehold', 'Leasehold')], max_length=10, null=True),
        ),
    ]
