# Generated by Django 3.1.5 on 2021-02-23 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0010_auto_20210223_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='customer',
        ),
        migrations.AlterField(
            model_name='house',
            name='appraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='borrower',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='current_owner',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='occupant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='project_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_rights_appraised',
            field=models.TextField(blank=True, null=True),
        ),
    ]
