# Generated by Django 3.1.5 on 2021-02-23 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0011_auto_20210223_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foundation',
            old_name='improvements',
            new_name='improvements_id',
        ),
        migrations.AddField(
            model_name='house',
            name='customer',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='appraiser',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appraiser', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='borrower',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='current_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='occupant',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Tenant', 'Tenant'), ('Vacant', 'Vacant')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Planned Unit Development', 'Pud'), ('Condominium', 'Condominium')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_rights_appraised',
            field=models.CharField(blank=True, choices=[('Fee Simple', 'Fee Simple'), ('Leasehold', 'Leasehold')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_year',
            field=models.IntegerField(blank=True, choices=[(2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985)], null=True),
        ),
    ]
