# Generated by Django 3.1.5 on 2021-02-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20210223_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='built_up',
            field=models.CharField(blank=True, choices=[('Over 75%', 'Over75'), ('25%-75%', 'Under75'), ('Under 25%', 'Under25')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='demand_supply',
            field=models.CharField(blank=True, choices=[('Shortage', 'Shortage'), ('Stable', 'Stable'), ('Declining', 'Declining')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='growth_rate',
            field=models.CharField(blank=True, choices=[('Rapid', 'Rapid'), ('Stable', 'Stable'), ('Slow', 'Slow')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(blank=True, choices=[('Urban', 'Urban'), ('Suburban', 'Suburban'), ('Rural', 'Rural')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='market_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='marketability_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='property_value',
            field=models.CharField(blank=True, choices=[('Increasing', 'Increasing'), ('Stable', 'Stable'), ('Slow', 'Slow')], max_length=15, null=True),
        ),
    ]
