# Generated by Django 3.1.5 on 2021-02-27 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20210226_1922'),
        ('webapp', '0013_auto_20210226_0026'),
    ]

    operations = [
    ]
