# Generated by Django 3.1.5 on 2021-03-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20210301_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offsite',
            name='offsite_alley',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private'), ('Neither', 'Neither')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_alley_note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_curb',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private'), ('Neither', 'Neither')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_curb_note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_sidewalk',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private'), ('Neither', 'Neither')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_sidewalk_note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_street',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private'), ('Neither', 'Neither')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_street_note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_streetlight_note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='offsite_streetlights',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private'), ('Neither', 'Neither')], max_length=10, null=True),
        ),
    ]
