# Generated by Django 3.1.5 on 2021-03-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20210301_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialsandcondition',
            old_name='materials_bath_floor',
            new_name='material_bath_floor',
        ),
        migrations.RenameField(
            model_name='materialsandcondition',
            old_name='materials_bath_wainscot',
            new_name='material_bath_wainscot',
        ),
        migrations.RenameField(
            model_name='materialsandcondition',
            old_name='materials_doors',
            new_name='material_doors',
        ),
        migrations.RenameField(
            model_name='materialsandcondition',
            old_name='materials_trim',
            new_name='material_trim',
        ),
        migrations.AlterField(
            model_name='materialsandcondition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
