# Generated by Django 3.1.5 on 2021-03-03 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20210301_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Foyer', 'Foyer'), ('Living Room', 'Living'), ('Dining Room', 'Dining'), ('Kitchen', 'Kitchen'), ('Den', 'Den'), ('Family Room', 'Family'), ('Recreation Room', 'Recreation'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bath'), ('Half bath', 'Halfbath'), ('Laundry Room', 'Laundry'), ('Basement', 'Basement'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RoomSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_bedrooms', models.IntegerField(blank=True, null=True)),
                ('num_bathrooms', models.FloatField(blank=True, null=True)),
                ('num_floors', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.house')),
            ],
        ),
    ]
