# Generated by Django 3.1.5 on 2021-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20210303_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionofimprovements',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionofimprovements',
            name='design_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionofimprovements',
            name='gutters_downspouts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionofimprovements',
            name='roof_surface',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionofimprovements',
            name='storm_screens',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionofimprovements',
            name='walls',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionofimprovements',
            name='win_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='built_up',
            field=models.CharField(blank=True, choices=[('Over 75%', 'Over 75%'), ('ABOVE25', '25%-75%'), ('UNDER25', 'Under 25%')], max_length=15, null=True),
        ),
    ]
