# Generated by Django 3.1.5 on 2021-03-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20210304_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pool', models.CharField(blank=True, max_length=50, null=True)),
                ('fireplace', models.CharField(blank=True, max_length=50, null=True)),
                ('patio', models.CharField(blank=True, max_length=50, null=True)),
                ('deck', models.CharField(blank=True, max_length=50, null=True)),
                ('fence', models.CharField(blank=True, max_length=50, null=True)),
                ('garage', models.CharField(blank=True, max_length=50, null=True)),
                ('basement', models.CharField(blank=True, max_length=50, null=True)),
                ('attic', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.house')),
            ],
        ),
        migrations.DeleteModel(
            name='HouseFeatures',
        ),
    ]
