# Generated by Django 3.1.5 on 2021-03-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_amenities_porch'),
        ('webapp', '0020_auto_20210303_0038'),
    ]

    operations = [
    ]
