# Generated by Django 3.1.5 on 2021-03-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_merge_20210305_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='kitchen_cabinets',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
