# Generated by Django 3.1.5 on 2021-03-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20210309_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offsite',
            name='site',
        ),
        migrations.AddField(
            model_name='offsite',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.house'),
        ),
        migrations.AlterField(
            model_name='offsite',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
